name: Check and Merge READMEs

on:
  schedule:
    - cron: '0 8 * * *'  # 每天8点触发
  workflow_dispatch:
    inputs:
      rebuild:
        description: '忽略构建记录以重新构建'
        required: false
        type: boolean
      donotpublish:
        description: '构建后不提交发布新版'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - userName: xisohi
            repoName: tvbox
            branchName: main
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check New Commit
        id: check_commit
        run: |
          # 获取最新提交的SHA值
          commitSHA=$(curl -sL "https://api.github.com/repos/${{ matrix.userName }}/${{ matrix.repoName }}/commits/${{ matrix.branchName }}" | jq -r '.sha')
          if [ $? -ne 0 ]; then
            echo "Failed to get commit from API"
            exit 1
          fi
          echo "commitSHA=$commitSHA" >> $GITHUB_ENV

          # 获取所有发布标签中的SHA值
          releaseList=$(curl -s "https://api.github.com/repos/${{ matrix.userName }}/${{ matrix.repoName }}/tags")
          if echo "$releaseList" | jq -r '.[] | .commit.sha' | grep -q "$commitSHA"; then
            echo "Latest commit SHA already exists in tags. Exiting workflow."
            echo "run_steps=false" >> $GITHUB_ENV
            exit 0
          else
            echo "New commit detected. Proceeding with further steps..."
            echo "run_steps=true" >> $GITHUB_ENV
          fi

      - name: Merge READMEs if there are new commits
        if: ${{ env.run_steps == 'true' }}
        run: |
          # 合并指定目录下的 README.md 文件内容
          cat 中兴/README.md >> /tmp/merged_readme.md
          echo -e "\n" >> /tmp/merged_readme.md
          cat 九联/README.md >> /tmp/merged_readme.md
          echo -e "\n" >> /tmp/merged_readme.md
          cat 创维/README.md >> /tmp/merged_readme.md
          echo -e "\n" >> /tmp/merged_readme.md
          cat 华为/README.md >> /tmp/merged_readme.md
          
          # 替换根目录下的 README.md 文件内容
          mv /tmp/merged_readme.md README.md
          git add README.md
          git commit -m "Merge READMEs from subdirectories"
          git push

      - name: Exit if no new commits
        if: ${{ env.run_steps == 'false' }}
        run: echo "No new commits in the repository. Exiting."