name: Check and Merge READMEs

on:
  schedule:
    - cron: '0 8 * * *'  # 每天8点触发
  workflow_dispatch:
    inputs:
      rebuild:
        description: '忽略构建记录以重新构建'
        required: false
        type: boolean
      donotpublish:
        description: '构建后不提交发布新版'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - userName: xisohi
            repoName: tvbox
            branchName: main
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          # 设置当前仓库的用户信息
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check New Commit
        id: check_commit
        run: |
          # 获取最新提交的SHA值
          commitSHA=$(curl -sL "https://api.github.com/repos/${{ matrix.userName }}/${{ matrix.repoName }}/commits/${{ matrix.branchName }}" | jq -r '.sha')
          if [ $? -ne 0 ]; then
            echo "Failed to get commit from API. Please check the URL and network connection."
            exit 1
          fi
          echo "commitSHA=$commitSHA" >> $GITHUB_ENV

          # 获取所有发布标签中的SHA值
          releaseList=$(curl -s "https://api.github.com/repos/${{ matrix.userName }}/${{ matrix.repoName }}/tags")
          if echo "$releaseList" | jq -r '.[] | .commit.sha' | grep -q "$commitSHA"; then
            echo "Latest commit SHA already exists in tags. Exiting workflow."
            echo "run_steps=false" >> $GITHUB_ENV
            exit 0
          else
            echo "New commit detected. Proceeding with further steps..."
            echo "run_steps=true" >> $GITHUB_ENV
          fi

      - name: Check if commit is already processed
        if: ${{ env.run_steps == 'true' }}
        id: check_processed
        run: |
          commitSHA=${{ env.commitSHA }}
          if grep -q "$commitSHA" README.md; then
            echo "Commit already processed. Exiting."
            echo "run_steps=false" >> $GITHUB_ENV
            exit 1
          else
            echo "Commit not processed. Proceeding with merge operation."
            echo "run_steps=true" >> $GITHUB_ENV
          fi

      - name: Merge READMEs if there are new commits
        if: ${{ env.run_steps == 'true' }}
        run: |
          # 定义要合并的目录和文件
          directories=("中兴" "九联" "创维" "华为")
          merged_file="/tmp/merged_readme.md"

          # 初始化合并文件
          > "$merged_file"

          # 遍历目录并合并 README.md 文件
          for dir in "${directories[@]}"; do
            readme_file="${dir}/README.md"
            if [ -f "$readme_file" ]; then
              cat "$readme_file" >> "$merged_file"
              echo -e "\n" >> "$merged_file"
            else
              echo "Warning: $readme_file does not exist. Skipping."
            fi
          done

          # 替换根目录下的 README.md 文件内容
          mv "$merged_file" README.md
          git add README.md
          git commit -m "Merge READMEs from subdirectories"
          git push

      - name: Exit if no new commits
        if: ${{ env.run_steps == 'false' }}
        run: echo "No new commits in the repository. Exiting."